sudo: required  
dist: trusty  
env:  
  - CLI_VERSION=latest DOTNET_CLI_TELEMETRY_OPTOUT=1 MAJOR_VER=0 MINOR_VER=3 BUILD_VER=3
os:  
  - linux
branches:  
  only:
    - master
install:  
  - export DOTNET_INSTALL_DIR="$PWD/.dotnetcli"
  - curl -sSL https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.sh | bash /dev/stdin --version "$CLI_VERSION" --install-dir "$DOTNET_INSTALL_DIR"
  - export PATH="$DOTNET_INSTALL_DIR:$PATH"
script:
  - dotnet restore
  - dotnet build -c Release src
  - dotnet publish -c Release src
after_success:
  - docker build -t dustinmoris/newshacker:$MAJOR_VER.$MINOR_VER.$BUILD_VER src/bin/Release/netcoreapp1.0/publish/.
  - docker tag dustinmoris/newshacker:$MAJOR_VER.$MINOR_VER.$BUILD_VER dustinmoris/newshacker:$MAJOR_VER
  - docker tag dustinmoris/newshacker:$MAJOR_VER.$MINOR_VER.$BUILD_VER dustinmoris/newshacker:$MAJOR_VER.$MINOR_VER
  - docker tag dustinmoris/newshacker:$MAJOR_VER.$MINOR_VER.$BUILD_VER dustinmoris/newshacker:latest
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push dustinmoris/newshacker:$MAJOR_VER.$MINOR_VER.$BUILD_VER
  - docker push dustinmoris/newshacker:$MAJOR_VER.$MINOR_VER
  - docker push dustinmoris/newshacker:$MAJOR_VER
  - docker push dustinmoris/newshacker:latest