language: csharp
sudo: required
dist: trusty
mono: none
dotnet: 1.0.0-preview2-003131
install:
  - export DOTNET_CLI_TELEMETRY_OPTOUT=1 
script:
  - dotnet restore
  - dotnet build -c Release src
  - dotnet publish -c Release src
deploy:
  provider: script
  script: deploy.sh
  skip_cleanup: true
  on:
    tags: true